baseURL = "http://blog.damnops.com"
languageCode = "en-us"
title = "dAmNOps"
copyright = "dAmNOps.com"
disableKinds = ["section"]
theme = "diary"
# googleAnalytics = "UA-123-45"
#googleAnalytics = ""      # UA-XXXXXXXX-X



[params]
subtitle = "You DAMN Ops"
enableGitalk = true

[params.gitalk]
  owner = "phoenix-zhu"
  repo = "blog"
  client_id = "7e7716d22bc7b477d0ce"
  client_secret = "a50211cca027a925ea5f27c77a71fe7d78ba19fc"

[taxonomies]
   tag = "tags"
   category = "categories"
   chronology = "chronologies"

[[menu.main]]
url = "/categories"
name = "Categories"
weight = 1
[[menu.main]]
url = "/chronologies"
name = "Chronologies"
weight = 2
[[menu.main]]
url = "/tags"
name = "Tags"
weight = 50
[[menu.main]]
url = "/about-me"
name = "About Me"
weight = 100
